export const DUMMY_PARTNERS = [
  {
    uid: "p1",
    name: "Razlan Automotive Sdn Bhd",
    email: "razlan@partnermail.com",
    role: "fleet_owner",
    is_active: true,
    is_superuser: false,
    profile: {
      title: "Fleet Owner",
      bio: "Operates a fleet of 12 vehicles across the Klang Valley.",
      years_experience: 5,
      phone: "+60 3-7890 1234",
      whatsapp: "+60 12-890 1234",
      city: "Subang Jaya",
      country: "Malaysia",
      profile_picture: null,
      cv: null,
    },
  },
  {
    uid: "p2",
    name: "Amirul Hakim",
    email: "amirul@gmail.com",
    role: "individual",
    is_active: true,
    is_superuser: false,
    profile: {
      title: "Individual Owner",
      bio: "Renting out 2 personal vehicles part-time.",
      years_experience: 2,
      phone: "+60 11-234 5678",
      whatsapp: "+60 11-234 5678",
      city: "Petaling Jaya",
      country: "Malaysia",
      profile_picture: null,
      cv: null,
    },
  },
  {
    uid: "p3",
    name: "Syarikat Wangsa Fleet",
    email: "wangsa@fleetco.my",
    role: "fleet_owner",
    is_active: false,
    is_superuser: false,
    profile: {
      title: "Fleet Owner",
      bio: null,
      years_experience: 8,
      phone: "+60 3-4567 8901",
      whatsapp: null,
      city: "Ampang",
      country: "Malaysia",
      profile_picture: null,
      cv: null,
    },
  },
  {
    uid: "p4",
    name: "Noraini Binti Hamid",
    email: "noraini@personal.com",
    role: "individual",
    is_active: true,
    is_superuser: false,
    profile: null,
  },
];
