export const DUMMY_BRANDS = [
  {
    uid: "b1",
    name: "Toyota",
    country_of_origin: "Japan",
    description: "World's largest automaker, known for reliability and value across all segments.",
    is_active: true,
    logo: null,
    vehicle_count: 0,
  },
  {
    uid: "b2",
    name: "BMW",
    country_of_origin: "Germany",
    description: "Premium German automaker delivering performance-driven luxury vehicles.",
    is_active: true,
    logo: null,
    vehicle_count: 0,
  },
  {
    uid: "b3",
    name: "Honda",
    country_of_origin: "Japan",
    description: "Japanese brand celebrated for fuel efficiency and long-term durability.",
    is_active: true,
    logo: null,
    vehicle_count: 0,
  },
  {
    uid: "b4",
    name: "Mercedes-Benz",
    country_of_origin: "Germany",
    description: "Iconic luxury brand synonymous with prestige and engineering excellence.",
    is_active: false,
    logo: null,
    vehicle_count: 0,
  },
  {
    uid: "b5",
    name: "Proton",
    country_of_origin: "Malaysia",
    description: "Malaysia's national car brand, offering affordable and practical vehicles.",
    is_active: true,
    logo: null,
    vehicle_count: 0,
  },
  {
    uid: "b6",
    name: "Perodua",
    country_of_origin: "Malaysia",
    description: "Malaysia's best-selling car brand, known for compact and economical models.",
    is_active: true,
    logo: null,
    vehicle_count: 0,
  },
];
