export const DUMMY_MANAGERS = [
  {
    uid: "mg1",
    name: "Nurul Ain Binti Yusof",
    email: "nurul@jomdrivo.com",
    role: "account_manager",
    is_active: true,
    profile: {
      title: "Senior Account Manager",
      department: "Fleet Operations",
      assigned_area: "Kuala Lumpur & Selangor",
      bio: "Manages customer accounts and coordinates fleet rental bookings across the Klang Valley region.",
      years_experience: 4,
      phone: "+60 11-987 6543",
      whatsapp: "+60 11-987 6543",
      city: "Petaling Jaya",
      country: "Malaysia",
      profile_picture: null,
    },
  },
  {
    uid: "mg2",
    name: "Hafiz Zulkifli",
    email: "hafiz@jomdrivo.com",
    role: "account_manager",
    is_active: false,
    profile: {
      title: "Account Manager",
      department: "Customer Relations",
      assigned_area: "Shah Alam",
      bio: null,
      years_experience: 1,
      phone: "+60 16-111 2222",
      whatsapp: null,
      city: "Shah Alam",
      country: "Malaysia",
      profile_picture: null,
    },
  },
  {
    uid: "mg3",
    name: "Farhan Izzatul Syukri",
    email: "farhan@jomdrivo.com",
    role: "account_manager",
    is_active: true,
    profile: {
      title: "Account Manager",
      department: "Sales",
      assigned_area: "Penang",
      bio: "Focused on growing the partner network and managing rental accounts in the northern region.",
      years_experience: 2,
      phone: "+60 14-222 3333",
      whatsapp: "+60 14-222 3333",
      city: "George Town",
      country: "Malaysia",
      profile_picture: null,
    },
  },
  {
    uid: "mg4",
    name: "Suria Tan Mei Ling",
    email: "suria@jomdrivo.com",
    role: "account_manager",
    is_active: true,
    profile: {
      title: "Account Manager",
      department: "Fleet Operations",
      assigned_area: "Johor Bahru",
      bio: "Oversees vehicle listings and partner relationships in the southern corridor.",
      years_experience: 3,
      phone: "+60 17-444 5555",
      whatsapp: "+60 17-444 5555",
      city: "Johor Bahru",
      country: "Malaysia",
      profile_picture: null,
    },
  },
];

export const MANAGER_DEPARTMENTS = [
  "Fleet Operations",
  "Customer Relations",
  "Sales",
  "Finance",
  "Operations",
];
