import { VEHICLE_CATEGORIES, VEHICLE_TRANSMISSIONS, VEHICLE_FUEL_TYPES } from "hooks/vehicles/_dummy";

export { VEHICLE_CATEGORIES as MODEL_CATEGORIES, VEHICLE_TRANSMISSIONS as MODEL_TRANSMISSIONS, VEHICLE_FUEL_TYPES as MODEL_FUEL_TYPES };

export const DUMMY_MODELS = [
  {
    uid: "m1",
    brand_uid: "b1",
    brand_name: "Toyota",
    name: "Camry",
    year_start: 2018,
    year_end: null,
    category: "Sedan",
    transmission: "Automatic",
    fuel_type: "Petrol",
    seats: 5,
    created_at: "2024-01-10",
  },
  {
    uid: "m2",
    brand_uid: "b1",
    brand_name: "Toyota",
    name: "Hiace",
    year_start: 2015,
    year_end: null,
    category: "Van",
    transmission: "Manual",
    fuel_type: "Diesel",
    seats: 12,
    created_at: "2024-01-11",
  },
  {
    uid: "m3",
    brand_uid: "b1",
    brand_name: "Toyota",
    name: "Fortuner",
    year_start: 2016,
    year_end: null,
    category: "SUV",
    transmission: "Automatic",
    fuel_type: "Diesel",
    seats: 7,
    created_at: "2024-01-12",
  },
  {
    uid: "m4",
    brand_uid: "b2",
    brand_name: "BMW",
    name: "3 Series",
    year_start: 2019,
    year_end: null,
    category: "Sedan",
    transmission: "Automatic",
    fuel_type: "Petrol",
    seats: 5,
    created_at: "2024-01-13",
  },
  {
    uid: "m5",
    brand_uid: "b2",
    brand_name: "BMW",
    name: "5 Series",
    year_start: 2020,
    year_end: null,
    category: "Luxury",
    transmission: "Automatic",
    fuel_type: "Petrol",
    seats: 5,
    created_at: "2024-01-14",
  },
  {
    uid: "m6",
    brand_uid: "b3",
    brand_name: "Honda",
    name: "CR-V",
    year_start: 2017,
    year_end: null,
    category: "SUV",
    transmission: "Automatic",
    fuel_type: "Petrol",
    seats: 7,
    created_at: "2024-01-15",
  },
  {
    uid: "m7",
    brand_uid: "b3",
    brand_name: "Honda",
    name: "Odyssey",
    year_start: 2014,
    year_end: 2022,
    category: "MPV",
    transmission: "Automatic",
    fuel_type: "Petrol",
    seats: 8,
    created_at: "2024-01-16",
  },
  {
    uid: "m8",
    brand_uid: "b3",
    brand_name: "Honda",
    name: "City",
    year_start: 2020,
    year_end: null,
    category: "Sedan",
    transmission: "Automatic",
    fuel_type: "Petrol",
    seats: 5,
    created_at: "2024-01-17",
  },
  {
    uid: "m9",
    brand_uid: "b5",
    brand_name: "Proton",
    name: "X70",
    year_start: 2018,
    year_end: null,
    category: "SUV",
    transmission: "Automatic",
    fuel_type: "Petrol",
    seats: 5,
    created_at: "2024-01-18",
  },
  {
    uid: "m10",
    brand_uid: "b5",
    brand_name: "Proton",
    name: "Saga",
    year_start: 2016,
    year_end: null,
    category: "Sedan",
    transmission: "Automatic",
    fuel_type: "Petrol",
    seats: 5,
    created_at: "2024-01-19",
  },
  {
    uid: "m11",
    brand_uid: "b6",
    brand_name: "Perodua",
    name: "Myvi",
    year_start: 2017,
    year_end: null,
    category: "Hatchback",
    transmission: "Automatic",
    fuel_type: "Petrol",
    seats: 5,
    created_at: "2024-01-20",
  },
  {
    uid: "m12",
    brand_uid: "b6",
    brand_name: "Perodua",
    name: "Bezza",
    year_start: 2016,
    year_end: null,
    category: "Sedan",
    transmission: "Automatic",
    fuel_type: "Petrol",
    seats: 5,
    created_at: "2024-01-21",
  },
];
