export const DUMMY_USERS = [
  {
    uid: "u1",
    name: "Ahmad Razif",
    email: "ahmad@jomdrivo.com",
    role: "admin",
    is_active: true,
    is_superuser: true,
    profile: {
      title: "Platform Administrator",
      bio: "Oversees all platform operations and user management.",
      years_experience: 7,
      phone: "+60 12-345 6789",
      whatsapp: "+60 12-345 6789",
      city: "Kuala Lumpur",
      country: "Malaysia",
      profile_picture: null,
      cv: null,
    },
  },
  {
    uid: "u2",
    name: "Nurul Ain Binti Yusof",
    email: "nurul@jomdrivo.com",
    role: "account_manager",
    is_active: true,
    is_superuser: false,
    profile: {
      title: "Account Manager",
      bio: "Manages customer accounts and rental bookings.",
      years_experience: 3,
      phone: "+60 11-987 6543",
      whatsapp: "+60 11-987 6543",
      city: "Petaling Jaya",
      country: "Malaysia",
      profile_picture: null,
      cv: null,
    },
  },
  {
    uid: "u3",
    name: "Hafiz Zulkifli",
    email: "hafiz@jomdrivo.com",
    role: "account_manager",
    is_active: false,
    is_superuser: false,
    profile: {
      title: "Account Manager",
      bio: null,
      years_experience: 1,
      phone: "+60 16-111 2222",
      whatsapp: null,
      city: "Shah Alam",
      country: "Malaysia",
      profile_picture: null,
      cv: null,
    },
  },
  {
    uid: "u4",
    name: "Siti Rahayu",
    email: "siti@jomdrivo.com",
    role: "admin",
    is_active: true,
    is_superuser: false,
    profile: null,
  },
];
