export const VEHICLE_FEATURES = [
  "GPS", "Bluetooth", "Reverse Camera", "Child Seat",
  "Sunroof", "Leather Seats", "USB Charging", "Toll Card",
  "Full Tank Policy", "Dashcam",
];

export const VEHICLE_CATEGORIES   = ["Sedan", "SUV", "MPV", "Hatchback", "Luxury", "Van", "Truck", "Pick-up"];
export const VEHICLE_FUEL_TYPES    = ["Petrol", "Diesel", "Electric", "Hybrid"];
export const VEHICLE_TRANSMISSIONS = ["Automatic", "Manual"];
export const VEHICLE_STATUSES      = ["available", "rented", "maintenance", "inactive"];

export const STATUS_META = {
  available:   { label: "Available",   bg: "bg-green-50",  text: "text-green-600",  border: "border-green-200",  dot: "bg-green-500"  },
  rented:      { label: "Rented",      bg: "bg-orange-50", text: "text-orange-600", border: "border-orange-200", dot: "bg-orange-500" },
  maintenance: { label: "Maintenance", bg: "bg-red-50",    text: "text-red-500",    border: "border-red-200",    dot: "bg-red-500"    },
  inactive:    { label: "Inactive",    bg: "bg-slate-50",  text: "text-slate-400",  border: "border-slate-200",  dot: "bg-slate-300"  },
};

export const DUMMY_VEHICLES = [
  {
    uid: "v1",
    brand: "Toyota",
    model: "Camry",
    year: 2022,
    category: "Sedan",
    fuel_type: "Petrol",
    transmission: "Automatic",
    seats: 5,
    color: "Pearl White",
    plate_number: "WXY 1234",
    daily_rate: 180,
    location: "Kuala Lumpur",
    status: "available",
    is_active: true,
    mileage: 28500,
    insurance_expiry: "2025-12-31",
    road_tax_expiry: "2025-06-30",
    features: ["GPS", "Bluetooth", "Reverse Camera"],
    description: "Well-maintained family sedan, perfect for city and highway driving.",
    partner_uid: "p1",
    images: null,
    rating: 4.9,
    reviews: 124,
  },
  {
    uid: "v2",
    brand: "Honda",
    model: "CR-V",
    year: 2023,
    category: "SUV",
    fuel_type: "Petrol",
    transmission: "Automatic",
    seats: 7,
    color: "Lunar Silver",
    plate_number: "VJJ 5678",
    daily_rate: 250,
    location: "Petaling Jaya",
    status: "available",
    is_active: true,
    mileage: 12300,
    insurance_expiry: "2026-03-31",
    road_tax_expiry: "2026-01-31",
    features: ["GPS", "Bluetooth", "Reverse Camera", "USB Charging"],
    description: "Spacious 7-seater SUV, ideal for family trips.",
    partner_uid: "p2",
    images: null,
    rating: 4.8,
    reviews: 89,
  },
  {
    uid: "v3",
    brand: "BMW",
    model: "3 Series",
    year: 2021,
    category: "Luxury",
    fuel_type: "Petrol",
    transmission: "Automatic",
    seats: 5,
    color: "Alpine White",
    plate_number: "WA 9012",
    daily_rate: 450,
    location: "KLCC",
    status: "rented",
    is_active: true,
    mileage: 45200,
    insurance_expiry: "2025-09-30",
    road_tax_expiry: "2025-09-30",
    features: ["GPS", "Leather Seats", "Sunroof", "Bluetooth", "Dashcam"],
    description: "Premium luxury sedan with sporty performance.",
    partner_uid: "p1",
    images: null,
    rating: 4.9,
    reviews: 56,
  },
  {
    uid: "v4",
    brand: "Toyota",
    model: "Hiace",
    year: 2020,
    category: "Van",
    fuel_type: "Diesel",
    transmission: "Manual",
    seats: 12,
    color: "White",
    plate_number: "BJB 3456",
    daily_rate: 320,
    location: "Subang Jaya",
    status: "available",
    is_active: true,
    mileage: 88000,
    insurance_expiry: "2025-08-31",
    road_tax_expiry: "2025-08-31",
    features: ["USB Charging", "Toll Card"],
    description: "High-capacity van suited for group travel and corporate transfers.",
    partner_uid: "p3",
    images: null,
    rating: 4.7,
    reviews: 43,
  },
  {
    uid: "v5",
    brand: "Perodua",
    model: "Myvi",
    year: 2023,
    category: "Hatchback",
    fuel_type: "Petrol",
    transmission: "Automatic",
    seats: 5,
    color: "Red",
    plate_number: "WPL 2345",
    daily_rate: 90,
    location: "Cheras",
    status: "available",
    is_active: true,
    mileage: 9800,
    insurance_expiry: "2026-06-30",
    road_tax_expiry: "2026-06-30",
    features: ["Bluetooth", "Reverse Camera"],
    description: "Popular compact hatchback, great for city driving and budget travel.",
    partner_uid: "p4",
    images: null,
    rating: 4.6,
    reviews: 210,
  },
  {
    uid: "v6",
    brand: "Honda",
    model: "Odyssey",
    year: 2019,
    category: "MPV",
    fuel_type: "Petrol",
    transmission: "Automatic",
    seats: 8,
    color: "Lunar Silver",
    plate_number: "WWW 6789",
    daily_rate: 290,
    location: "Ampang",
    status: "maintenance",
    is_active: true,
    mileage: 72000,
    insurance_expiry: "2025-11-30",
    road_tax_expiry: "2025-11-30",
    features: ["GPS", "Bluetooth", "USB Charging", "Child Seat"],
    description: "Comfortable 8-seater MPV, perfect for family outings.",
    partner_uid: "p2",
    images: null,
    rating: 4.8,
    reviews: 67,
  },
];
